AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Función para crear PDFs de cotizaciones (parametrizada por ambiente).

# Definimos los parámetros que nuestro pipeline le pasará al template
Parameters:
  Environment:
    Type: String
    Description: El nombre del ambiente (staging o production).
    Default: staging
  DbHost:
    Type: String
    Description: El host de la base de datos.
  DbPort:
    Type: String
    Description: El puerto de la base de datos.
  DbSecretName:
    Type: String
    Description: El nombre del secreto en AWS Secrets Manager.
  S3BucketName:
    Type: String
    Description: El nombre del bucket S3 para este ambiente.

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x

Resources:
  CreateQuotePdfFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "prospect-create-quote-pdf-${Environment}" # Nombre de función dinámico
      CodeUri: dist/
      Handler: app.handler
      AutoPublishAlias: live # Un alias genérico, el stage del API Gateway le dará el contexto
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
      
      # Usamos los parámetros para definir las variables de entorno
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
          DB_SECRET_NAME: !Ref DbSecretName
          S3_BUCKET_NAME: !Ref S3BucketName
      
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /prospect/create-quote
            Method: post

Outputs:
  ApiUrl:
    Description: "URL del API Gateway para invocar la función"
    Value: !Sub "https://#{ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-quote"